language: android

jdk:
    - oraclejdk8

before_install:
    - chmod +x gradlew

script: ./gradlew :app:lint :app:test

android:
    components:
        - build-tools-23.0.3
        - android-23
        - extra-android-support
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository

branches:
    only:
        - master
        - develop

notifications:
    email: false